Добавляет базовую стилизацию всех страниц.
htmlacademy-htmlcss/2417021-sedona-1 pull request #3
Opened 2023-10-18 17:32 UTC by r3t4rdme

2023-10-19 20:35 UTC, Viktor-Rybakov commented on styles/styles.css
> +    font-family: "PT Sans";
В коде должно быть единообразие: либо два пробела, либо четыре. Либо табы.
Посмотри стайлгайд: http://codeguide.academy/html-css.html

2023-10-19 20:45 UTC, Viktor-Rybakov commented on styles/styles.css
> +    color: #000;
По стайлгайду в написании цвета тоже должно быть единообразие: лучше указывать 6 цифр, хотя если не смотреть на сатйлгайд, то 3 - это не ошибка

2023-10-19 20:47 UTC, Viktor-Rybakov commented on styles/styles.css
> +  background-color: #83B3D31F;
Тут лучше записать в формате rgba - так удобнее для чтнения. Чтобы понять, на сколько прозрачный бекграунд, это надо посчитать из 16ричной в 10ричную систему исчисления

2023-10-19 20:48 UTC, Viktor-Rybakov commented on styles/styles.css
> +  background-image: url(../images/house-vector.svg);
Еще можно указать свойство backgroung-size, чтобы картинку не распипячило случайно

2023-10-19 20:51 UTC, Viktor-Rybakov commented on styles/styles.css
> +  background-repeat: no-repeat;
Ещё нужно указать свойство background-position

2023-10-19 20:54 UTC, Viktor-Rybakov commented on styles/styles.css
> +  height: 485px;
Не ограничивай высоту блоков, потому что внутри может поменяться контент (может картинку вставят больше, может текста добавят) и тогда контент вылезет за пределы блока.
Лучше задай min-height, тогда будет минимальная высота (как правило, по макету) и у блока будет возможно расти по высоте в зависимости от содержимого

2023-10-19 20:55 UTC, Viktor-Rybakov commented on styles/styles.css
> +  height: 414.86px;
То же про высоту блока

2023-10-19 20:59 UTC, Viktor-Rybakov commented on styles/styles.css
> +  padding: 11.36px, 0px, 12.64px, 0px;
я бы не советовал использовать такие дробные значения. Для попадания в макет у нас есть допуски. А когда браузер рендерит дробные, может отображать какие-то элементы размыленно

2023-10-19 21:01 UTC, Viktor-Rybakov commented on styles/styles.css
> +    background-image: url(../images/breadcrumbs-home-logo.svg);
нужно указать свойства:
background-position, size, repeat

2023-10-19 21:02 UTC, Viktor-Rybakov commented on styles/styles.css
> +    background-image: url(../images/breadcrumbs-arrow-2.svg);
то же, что и в предыдущей иконке

2023-10-19 21:03 UTC, Viktor-Rybakov commented on styles/styles.css
> +input[type="email"] {
а почему тут селектор не по классу?

2023-10-19 21:22 UTC, Viktor-Rybakov requested changes
Нужно немного поправить, ззамечаний немного, я их указывал только в одном месте, но многие из ни встречаются о многих местах

2023-12-11 13:24 UTC, Viktor-Rybakov commented on styles/styles.css
> +  max-width: 1280px;
обычно боди так по ширине не ограничивают, оно занимает всю ширину браузера.
На макете показано 1280 - это просто для того, чтобы показать, что есть контент шириной 1200 и слева-справа торчит серая подложка - это как раз боди

2023-12-11 13:25 UTC, Viktor-Rybakov commented on styles/styles.css
> +  max-width: 1280px;
И лучше перенеси стили по тегу вверх, потому что они глобальные, чтобы былы сразу на виду

2023-12-11 13:29 UTC, Viktor-Rybakov commented on styles/styles.css
> +  width: 44px;
Ширину лучше задать ссылке внутри, на элементу списка.

2023-12-11 13:32 UTC, Viktor-Rybakov commented on styles/styles.css
> +  padding: 51px 371px 82px;
Для изображения это внешние, а не внутренние отступы

2023-12-11 13:33 UTC, Viktor-Rybakov commented on styles/styles.css
> +  padding: 51px 371px 82px;
Их можно перенести на родительский див - там они будут внутренними

2023-12-11 13:35 UTC, Viktor-Rybakov commented on styles/styles.css
> +  background-image: url(../images/footer-background.jpg);
Мне кажется, тут перепутано изображение

2023-12-11 13:37 UTC, Viktor-Rybakov commented on styles/styles.css
> +.footer-contacts-address-phone {
Тут нужно определить font-style, потому что address задает италик (наклонный)

2023-12-11 13:38 UTC, Viktor-Rybakov commented on styles/styles.css
> +  background-image: url(../images/catalog-index-background.jpg);
По макету другая картинка

2023-12-11 13:39 UTC, Viktor-Rybakov commented on styles/styles.css
> +  background-position: auto;
background-position: auto; - такого значения нет... можно поставить center

2023-12-11 13:41 UTC, Viktor-Rybakov commented on styles/styles.css
> +  margin-bottom: 20px;
А если карточек будет 7 - сработает?
Попробуй вместо margin у карточки использовать свойство gap у flex-контейнера

2023-12-19 21:28 UTC, r3t4rdme commented on styles/styles.css
> +  background-image: url(../images/catalog-index-background.jpg);
А откуда ее взять? не вижу возможности экспорта из макета(
По сути, это же то же изображение, только заблюренное?

2023-12-21 21:19 UTC, merged